server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.129:8848
service-url:
  nacos-user-service: http://nacos-payment-provider